export const GlobalContent = {
  "English": {
    home: "Home",
    movies: "Movies",
    favorites: "Favorites",
    settings: "Settings",
    popular: "Popular",
    topRated: "Top Rated",
    upcoming: "Upcoming",
    nowPlaying: "Now Playing",
    search: "Search",
    searchPlaceholder: "Search for movies...",
    noMoviesFound: "No movies found",
    writeYourMovie: "Write your movie",
    noFavoritesFound: "No favorites found",
    darkMode: "Dark theme",
    language: "Language"
  },
  "Spanish": {
    home: "Inicio",
    movies: "Películas",
    favorites: "Favoritos",
    settings: "Ajustes",
    popular: "Popular",
    topRated: "Más valoradas",
    upcoming: "Próximas",
    nowPlaying: "En cines",
    search: "Buscar",
    searchPlaceholder: "Buscar películas...",
    noMoviesFound: "No se encontraron películas",
    writeYourMovie: "Escribe tu película",
    noFavoritesFound: "No se encontraron favoritos",
    darkMode: "Modo oscuro",
    language: "Idioma"
  },
  "French": {
    home: "Accueil",
    movies: "Films",
    favorites: "Favoris",
    settings: "Paramètres",
    popular: "Populaire",
    topRated: "Les mieux notés",
    upcoming: "À venir",
    nowPlaying: "En cours",
    search: "Rechercher",
    searchPlaceholder: "Rechercher des films...",
    noMoviesFound: "Aucun film trouvé",
    writeYourMovie: "Écrivez votre film",
    noFavoritesFound: "Aucun favori trouvé",
    darkMode: "Mode sombre",
    language: "Langue"
  },
  "German": {
    home: "Startseite",
    movies: "Filme",
    favorites: "Favoriten",
    settings: "Einstellungen",
    popular: "Beliebt",
    topRated: "Top bewertet",
    upcoming: "Kommend",
    nowPlaying: "Aktuell",
    search: "Suche",
    searchPlaceholder: "Suche nach Filmen...",
    noMoviesFound: "Keine Filme gefunden",
    writeYourMovie: "Schreibe deinen Film",
    noFavoritesFound: "Keine Favoriten gefunden",
    darkMode: "Dunkles Thema",
    language: "Sprache"
  },
  "Arabic": {
    home: "الصفحة الرئيسية",
    movies: "أفلام",
    favorites: "المفضلة",
    settings: "الإعدادات",
    popular: "شعبية",
    topRated: "الأعلى تقييماً",
    upcoming: "قادم",
    nowPlaying: "يعرض الآن",
    search: "بحث",
    searchPlaceholder: "ابحث عن الأفلام...",
    noMoviesFound: "لم يتم العثور على أفلام",
    writeYourMovie: "اكتب فيلمك",
    noFavoritesFound: "لم يتم العثور على المفضلات",
    darkMode: "وضع الظلام",
    language: "لغة"
  }
};
